### ISSUE TITLE
Defective PACSTRAP_PACMAN_CONFIG_FILE

### ISSUE THREAD

**Issue by mterencelao** [PotatoMania/uconsole-cm3-arch-image-builder#2]
**EDIT:** I plugged in a bad fix instead of pointing the problem. I also tried replacing with `$repo`, and it works as well.

In [PACSTRAP_PACMAN_CONFIG_FILE](../tree/dev/resources/arch-stage0-pacman.conf):
```
[core]
Server = http://mirror.archlinuxarm.org/$arch/core

[extra]
Server = http://mirror.archlinuxarm.org/$arch/core
[alarm]
Server = http://mirror.archlinuxarm.org/$arch/core
```
Shouldn't `extra` and `alarm` point to their respective repositories instead of just `core`? I'm getting the following error:
```
error: failed retrieving file 'alarm.db' from mirror.archlinuxarm.org : The requested URL returned error: 404
error: failed retrieving file 'extra.db' from mirror.archlinuxarm.org : The requested URL returned error: 404
```

**Comment by PotatoMania** [comment]
Oops, indeed I made a mistake. It will be fixed soon. Thanks for reporting that.

**Comment by PotatoMania** [comment]
should be fixed by https://github.com/PotatoMania/uconsole-cm3-arch-image-builder/commit/c2950d00884c1d926776df7215447ef7d8e2ca50
